### ISSUE TITLE
Unable to open nested jar file 'BOOT-INF/lib/tomcat-embed-core-8.5.6.jar'

### ISSUE THREAD

**Issue by xia-fei** [opendingtalk/eapp-isv-quick-start-java#1]
mvn打包完之后
运行
D:\github\eapp-isv-quick-start-java>java -jar target/eapp-isv-quick-start-1.0.0.jar
Exception in thread "main" java.io.IOException: Unable to open nested jar file 'BOOT-INF/lib/tomcat-embed-core-8.5.6.jar'
        at org.springframework.boot.loader.jar.JarFile.getNestedJarFile(JarFile.java:252)
        at org.springframework.boot.loader.jar.JarFile.getNestedJarFile(JarFile.java:237)
        at org.springframework.boot.loader.archive.JarFileArchive.getNestedArchive(JarFileArchive.java:103)
        at org.springframework.boot.loader.archive.JarFileArchive.getNestedArchives(JarFileArchive.java:87)
        at org.springframework.boot.loader.ExecutableArchiveLauncher.getClassPathArchives(ExecutableArchiveLauncher.java:72)
        at org.springframework.boot.loader.Launcher.launch(Launcher.java:49)
        at org.springframework.boot.loader.JarLauncher.main(JarLauncher.java:58)
Caused by: java.io.IOException: Unable to find ZIP central directory records after reading 65792 bytes
        at org.springframework.boot.loader.jar.CentralDirectoryEndRecord.<init>(CentralDirectoryEndRecord.java:64)
        at org.springframework.boot.loader.jar.CentralDirectoryParser.parse(CentralDirectoryParser.java:51)
        at org.springframework.boot.loader.jar.JarFile.<init>(JarFile.java:118)
        at org.springframework.boot.loader.jar.JarFile.<init>(JarFile.java:106)
        at org.springframework.boot.loader.jar.JarFile.createJarFileFromFileEntry(JarFile.java:290)
        at org.springframework.boot.loader.jar.JarFile.createJarFileFromEntry(JarFile.java:260)
        at org.springframework.boot.loader.jar.JarFile.getNestedJarFile(JarFile.java:248)
        ... 6 more
出现这个错误

**Comment by xia-fei** [comment]
> mvn打包完之后
> 运行
> D:\github\eapp-isv-quick-start-java>java -jar target/eapp-isv-quick-start-1.0.0.jar
> Exception in thread "main" java.io.IOException: Unable to open nested jar file 'BOOT-INF/lib/tomcat-embed-core-8.5.6.jar'
> at org.springframework.boot.loader.jar.JarFile.getNestedJarFile(JarFile.java:252)
> at org.springframework.boot.loader.jar.JarFile.getNestedJarFile(JarFile.java:237)
> at org.springframework.boot.loader.archive.JarFileArchive.getNestedArchive(JarFileArchive.java:103)
> at org.springframework.boot.loader.archive.JarFileArchive.getNestedArchives(JarFileArchive.java:87)
> at org.springframework.boot.loader.ExecutableArchiveLauncher.getClassPathArchives(ExecutableArchiveLauncher.java:72)
> at org.springframework.boot.loader.Launcher.launch(Launcher.java:49)
> at org.springframework.boot.loader.JarLauncher.main(JarLauncher.java:58)
> Caused by: java.io.IOException: Unable to find ZIP central directory records after reading 65792 bytes
> at org.springframework.boot.loader.jar.CentralDirectoryEndRecord.(CentralDirectoryEndRecord.java:64)
> at org.springframework.boot.loader.jar.CentralDirectoryParser.parse(CentralDirectoryParser.java:51)
> at org.springframework.boot.loader.jar.JarFile.(JarFile.java:118)
> at org.springframework.boot.loader.jar.JarFile.(JarFile.java:106)
> at org.springframework.boot.loader.jar.JarFile.createJarFileFromFileEntry(JarFile.java:290)
> at org.springframework.boot.loader.jar.JarFile.createJarFileFromEntry(JarFile.java:260)
> at org.springframework.boot.loader.jar.JarFile.getNestedJarFile(JarFile.java:248)
> ... 6 more
> 出现这个错误

D:\github\eapp-isv-quick-start-java>mvn clean package -Dmaven.test.skip=true
[INFO] Scanning for projects...
[INFO]
[INFO] ------------------------------------------------------------------------
[INFO] Building eapp-isv-quick-start 1.0.0
[INFO] ------------------------------------------------------------------------
[INFO]
[INFO] --- maven-clean-plugin:2.6.1:clean (default-clean) @ eapp-isv-quick-start ---
[INFO] Deleting D:\github\eapp-isv-quick-start-java\target
[INFO]
[INFO] --- maven-resources-plugin:2.6:resources (default-resources) @ eapp-isv-quick-start ---
[INFO] Using 'UTF-8' encoding to copy filtered resources.
[INFO] Copying 1 resource
[INFO] Copying 0 resource
[INFO]
[INFO] --- maven-compiler-plugin:3.1:compile (default-compile) @ eapp-isv-quick-start ---
[INFO] Changes detected - recompiling the module!
[INFO] Compiling 7 source files to D:\github\eapp-isv-quick-start-java\target\classes
[WARNING] 读取D:\repository\org\apache\tomcat\embed\tomcat-embed-core\8.5.6\tomcat-embed-core-8.5.6.jar时出错; error in opening zip file
[WARNING] 读取D:\repository\org\apache\tomcat\embed\tomcat-embed-core\8.5.6\tomcat-embed-core-8.5.6.jar时出错; cannot read zip file
[INFO]
[INFO] --- maven-resources-plugin:2.6:testResources (default-testResources) @ eapp-isv-quick-start ---
[INFO] Not copying test resources
[INFO]
[INFO] --- maven-compiler-plugin:3.1:testCompile (default-testCompile) @ eapp-isv-quick-start ---
[INFO] Not compiling test sources
[INFO]
[INFO] --- maven-surefire-plugin:2.18.1:test (default-test) @ eapp-isv-quick-start ---
[INFO] Tests are skipped.
[INFO]
[INFO] --- maven-jar-plugin:2.6:jar (default-jar) @ eapp-isv-quick-start ---
[INFO] Building jar: D:\github\eapp-isv-quick-start-java\target\eapp-isv-quick-start-1.0.0.jar
[INFO]
[INFO] --- spring-boot-maven-plugin:1.4.2.RELEASE:repackage (default) @ eapp-isv-quick-start ---
[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 3.213 s
[INFO] Finished at: 2018-09-28T14:15:45+08:00
[INFO] Final Memory: 30M/211M
[INFO] ------------------------------------------------------------------------

**Comment by xia-fei** [comment]
本地这个jar包有问题.已解决
